import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cookieToInitialState } from "wagmi";
import AppKitProvider from "@/app/src/W3MProvider";
import { headers } from "next/headers";
import { config } from "@/app/src/W3MConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppKitProvider initialState={initialState}>{children}</AppKitProvider>
      </body>
    </html>
  );
}
